export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const TOGGLE_IANDE = "TOGGLE_IANDE";
export const TOGGLE_MODAL = "TOGGLE_MODAL";

export const ADD_INCOMES = "ADD_INCOMES";
export const ADD_EXPENSES = "ADD_EXPENSES";
export const REMOVE_INCOMES = "REMOVE_INCOMES";
export const REMOVE_EXPENSES = "REMOVE_EXPENSES";