export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const TOGGLE_IANDE = "TOGGLE_IANDE";
export const TOGGLE_INCOME_MODAL = "TOGGLE_INCOME_MODAL";
export const TOGGLE_EXPENSE_MODAL = "TOGGLE_EXPENSE_MODAL"